-- SQL 문장 작성 --

DROP TABLE BOARD;
CREATE TABLE BOARD(
	IDX INT NOT NULL AUTO_INCREMENT,
	MEMID VARCHAR(20) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	WRITER VARCHAR(30) NOT NULL,
	INDATE DATETIME DEFAULT NOW(),
	COUNT INT DEFAULT 0,
	PRIMARY KEY(IDX)
);

INSERT INTO BOARD(TITLE, CONTENT, WRITER) 
VALUES ('안녕하세요!','MY SQL 화이팅','준용쌤');

INSERT INTO BOARD(TITLE, CONTENT, WRITER) 
VALUES ('담주 팀편성','팀장 지원하실 분~?','명훈쌤');

INSERT INTO BOARD(TITLE, CONTENT, WRITER) 
VALUES ('오늘의 간식은!','버터와플','준용쌤');

INSERT INTO BOARD(TITLE, CONTENT, WRITER) 
VALUES ('SQLD 언제야?','이번주 토요일ㅜ','박한빈');

INSERT INTO BOARD(TITLE, CONTENT, WRITER) 
VALUES ('노티드 맛있지','우유가 근본','노티드');

SELECT * FROM BOARD;

-- 회원 테이블 --
CREATE TABLE MEMBER(
	MEMIDX INT NOT NULL,
	MEMID VARCHAR(20) NOT NULL,
	MEMPASSWORD VARCHAR(68) NOT NULL,
	MEMNAME VARCHAR(20) NOT NULL,
	MEMAGE INT,
	MEMGENDER VARCHAR(20),
	MEMEMAIL VARCHAR(50),
	MEMPROFILE VARCHAR(50),
	PRIMARY KEY(MEMID)
);

INSERT INTO MEMBER(MEMID, MEMPASSWORD,MEMNAME, MEMAGE,MEMGENDER,MEMEMAIL,MEMPROFILE) 
VALUES('admin','1234','관리자',20,'남자','admin@gmail.com','');

SELECT * from MEMBER;

-- 권한 테이블
-- Spring Security 에서는 member 테이블 안에 반드시 권한이 있어야한다.
-- 사용하지 않더라도 넣어주자
CREATE TABLE AUTH(
	NO INT NOT NULL AUTO_INCREMENT,
	MEMID VARCHAR(50) NOT NULL,
	AUTH VARCHAR(50) NOT NULL,
	PRIMARY KEY(NO),
	CONSTRAINT FK_MEMBER_AUTH FOREIGN KEY(MEMID)
	REFERENCES MEMBER(MEMID)
)

SELECT * FROM AUTH;
